name: Bad Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: msbuild GMFMODSimpleGrix.sln /property:Configuration=Release /p:WarningLevel=0
      working-directory: ./GMFMODSimpleGrix

    - name: Copy FMOD DLL
      run: copy GMFMODSimpleGrix\Release\GMFMODSimpleGrix.dll GMFMODSimple.dll

    - name: Build gex
      run: python build.py gm82snd.gej

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: gm82net.gex